//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cours()
        {
            this.Student_Courses = new HashSet<Student_Courses>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> Creation_data { get; set; }
        public Nullable<int> Instructor { get; set; }
        public string Lessons { get; set; }
    
        public virtual Category Category1 { get; set; }
        public virtual Instructor Instructor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Courses> Student_Courses { get; set; }
    }
}
